global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'vmagent'
    static_configs:
      - targets: [ 'vmagent:8429' ]
  - job_name: 'victoriametrics'
    static_configs:
      - targets: [ 'victoriametrics:8428' ]
  - job_name: 'node'
    static_configs:
      - targets:
          - '100.115.88.2:9100'  # Node Exporter
